travis:
  secure:
    BINSTAR_TOKEN: sxy9yxuyJRwlKJ6othTqHWTTmRgK7G7GyaOtXYmSyAXAjzBE4wQbGZuhhNzQG59DWAJS1OJAXYhko4GFs85QUaAe7RQzsLntMgbQ4y3JqOZ78z9BHl/RdT0dz+CmuYHwM3JB480PpFRIjUah0jxKYbijfSuv1LDB1UJY/rxXJgNzBhRGi83p07DzSBJJt8EHmGPDL5BZQ7vFP4hor0u0D1ykpt9qojZqhjzbH6v2x8QufWy6jAFh89P6tKOjdPwo8R6u06Ws+FE3V+QXg/ii+h0beauXVbdBHwMqV0f6ICudYyVG7XO+QX3g3II7J+bpJsfEdqu2xiDL/y+2TWQtgVAXPgnzmrotMlKjBiiHUQUioMeytNUUhhy9W9dFyWy4xdcohMUPkK0o6Uujk70gs1rD1DElzUGwheJdazYvgK37ydOEQVNLXCT+twMm6BmBhQENLrDjwrZQ7RfK2eEIbKOdg8dku1dSjSVDmfDqiRWN9Dc5D7FzpDeHv7aaQc3bqwTY0x8HGXsQCYFaTqeMgl2T0HhlIWrqkQ2q79sZkzs7135UeXuXacFyIXB7c6Qev3wvF2Cowuwl0WQs/kf5vXvN53PMGzotLZ32nmtlMw9dyhDAhBLXUf+jJwYzPf+QE/RHwplY+33QhyJ4pD2SpZAig4yyNqxb4dS2OlDlq1U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
