travis:
  secure:
    BINSTAR_TOKEN: D1+0bn3nmtm1Bdbol5HBuEaEfDHV9PB9FEEP9/TQahdjUzYSxKHPXu1FTc1HnoEhpylu70i0FnM6QcphFYsu3Js/X2FyI4NzrixJExSVA4Q1sOOPFFgGD9RAlXYujGw7weOLyR4OticlzX6BTKYCkmKpmX+ghZSd0rOfWIK0HA27r41X/YNMUV0UcN8mIuzZwzm9D8wfSTs5MgSjUDZSHVBXvzzZyFjUOeRHAiGERxUQxcRb6zJ9ChUZzvbTcjyZWYZ4QMTDp2EM9d7LbvGuRE0IIY7QjfKWBLMLYxbd7CMGv4Yd31EO8TqgxYZNLVv4EoXAHoGfuhGT5SOkPeePJC+36kKXyo2ILhf6SRZJLbXEYrmERLexP+jzgvyDcUJ0iBtgFqnRKaRbBa36d6xERwlYRVbbWA7cHEyTbay5w+Pvw63xtNCud/b9zuRmomxMC8yGRakXqrK6GFC6RXIrFgXt0g6S1uuAVC/Zf+g3IRhrwfN7vbYyNDr1pRXXRmLdzcAxx3XAQd751nYFhOQ8TmIUBMxIq7BanTVtsHzAPGxGF3aM8kiBwyM0YUqQapCtWt8oe2Es28AHL618G6AJ6MB0CVqW+bRPlf6N+XPQELMs/e4ulstXlkFyiUlRORiO4l3ha/rn1MKYdWcbDJTrEUzu6n9SWSSV0DuQu4AaN60=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
